name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! This is your first issue. Feel free to ask questions or share your ideas here. We're glad to have you on board!"
        pr-message: "Hi! Thanks for your first pull request. We appreciate your contribution and are ready to discuss any changes or additions you've made."
